# -------- Generated by configure -----------

CC := powerpc-eabi-gcc
CXX := powerpc-eabi-g++
CFLAGS := -g -W -Wno-unused-parameter -Wno-empty-body -mrvl -mcpu=750 -meabi -mhard-float -ffunction-sections -fdata-sections -fmodulo-sched -fuse-cxa-atexit -I/c/devkitPro/libogc/include -Os -Wuninitialized
CXXFLAGS := $(CFLAGS)
LD := powerpc-eabi-g++
LIBS +=  -lgxflux -ldi -liso9660 -ltinysmb -lfat -lwiiuse -lbte -logc -lwiikeyboard -ldb -lm  -lmad
RANLIB := powerpc-eabi-ranlib
STRIP := powerpc-eabi-strip
AR := powerpc-eabi-ar cru
AS := powerpc-eabi-as
ASFLAGS := 
WINDRES := powerpc-eabi-windres
WINDRESFLAGS := 
STAGINGPATH=staging
WIN32PATH=c:/scummvm
AOS4PATH=Games:ScummVM
STATICLIBPATH=/sw

BACKEND := wii
MODULES +=  backends/platform/wii
MODULE_DIRS += 
EXEPRE := 
EXEEXT := .elf
NASM := 
NASMFLAGS := 

prefix = /usr/local
exec_prefix = ${prefix}
bindir = ${exec_prefix}/bin
libdir = ${exec_prefix}/lib
datarootdir = ${prefix}/share
datadir = ${datarootdir}/scummvm
mandir = ${datarootdir}/man
docdir = ${datarootdir}/doc/scummvm


HAVE_GCC = 1
HAVE_GCC3 = 1
CXX_UPDATE_DEP_FLAG = -MMD -MF "$(*D)/$(DEPDIR)/$(*F).d" -MQ "$@" -MP
GAMECUBE = 0
# VERBOSE_BUILD = 1
# USE_ELF_LOADER = 1
# DYNAMIC_MODULES = 1
USE_MT32EMU = 1
USE_RGB_COLOR = 1
USE_SAVEGAME_TIMESTAMP = 1
# USE_SCALERS = 1
# USE_HQ_SCALERS = 1
# USE_VORBIS = 1
# USE_TREMOR = 1
# USE_FLAC = 1
USE_MAD = 1
# USE_PNG = 1
# USE_THEORADEC = 1
# USE_FAAD = 1
# USE_ZLIB = 1
# USE_FREETYPE2 = 1
# USE_OPENGL = 1
# USE_GLES = 1
# USE_NASM = 1
ENABLE_VKEYBD = 1
# ENABLE_KEYMAPPER = 1
USE_TRANSLATION = 1
USE_TASKBAR = 1
USE_BINK = 1
# USE_UPDATES = 1
ENABLE_SCUMM = STATIC_PLUGIN
ENABLE_SCUMM_7_8 = 1
ENABLE_HE = 1
ENABLE_AGI = STATIC_PLUGIN
ENABLE_AGOS = STATIC_PLUGIN
ENABLE_AGOS2 = 1
ENABLE_CGE = STATIC_PLUGIN
ENABLE_CINE = STATIC_PLUGIN
# ENABLE_COMPOSER
ENABLE_CRUISE = STATIC_PLUGIN
ENABLE_DRACI = STATIC_PLUGIN
ENABLE_DRASCULA = STATIC_PLUGIN
# ENABLE_DREAMWEB
ENABLE_GOB = STATIC_PLUGIN
ENABLE_GROOVIE = STATIC_PLUGIN
# ENABLE_GROOVIE2
ENABLE_HUGO = STATIC_PLUGIN
ENABLE_KYRA = STATIC_PLUGIN
ENABLE_LOL = 1
# ENABLE_EOB
# ENABLE_LASTEXPRESS
ENABLE_LURE = STATIC_PLUGIN
ENABLE_MADE = STATIC_PLUGIN
ENABLE_MOHAWK = STATIC_PLUGIN
# ENABLE_CSTIME
# ENABLE_RIVEN
# ENABLE_MYST
ENABLE_PARALLACTION = STATIC_PLUGIN
ENABLE_QUEEN = STATIC_PLUGIN
ENABLE_SAGA = STATIC_PLUGIN
ENABLE_IHNM = 1
# ENABLE_SAGA2
ENABLE_SCI = STATIC_PLUGIN
# ENABLE_SCI32
ENABLE_SKY = STATIC_PLUGIN
ENABLE_SWORD1 = STATIC_PLUGIN
ENABLE_SWORD2 = STATIC_PLUGIN
# ENABLE_SWORD25
ENABLE_TEENAGENT = STATIC_PLUGIN
# ENABLE_TESTBED
ENABLE_TINSEL = STATIC_PLUGIN
# ENABLE_TOLTECS
ENABLE_TOON = STATIC_PLUGIN
ENABLE_TOUCHE = STATIC_PLUGIN
ENABLE_TSAGE = STATIC_PLUGIN
ENABLE_TUCKER = STATIC_PLUGIN

INCLUDES +=  
OBJS += 
DEFINES +=  -DPPC_TARGET -D__WII__ -DGEKKO -DDATA_PATH=\"${datarootdir}/scummvm\" -DPLUGIN_DIRECTORY=\"${exec_prefix}/lib/scummvm\"
LDFLAGS +=  -mrvl -mcpu=750 -L/c/devkitPro/libogc/lib/wii -logc



port_mk = backends/platform/wii/wii.mk

SAVED_CONFIGFLAGS  := --host=wii --with-flac-prefix=/c/devkitPro/3rd/wii --with-tremor-prefix=/c/devkitPro/3rd/wii
SAVED_LDFLAGS      := 
SAVED_CXX          := 
SAVED_CXXFLAGS     := 
SAVED_CPPFLAGS     := 
SAVED_ASFLAGS      := 
SAVED_WINDRESFLAGS := 
